### ISSUE TITLE
Issue with disposing collection view bind

### ISSUE THREAD

**Issue by bmetitiri** [ReactiveKit/Bond#416]
I have a `UITableView` where some cells contain a `UICollectionView`. In `cellForRowAt` on my table view I am binding a `MutableObservableArray` to the collection view in the cell, disposing of it in the bag for the table cell. Then in the table cell's `prepareForReuse` I am disposing it's bag to clear this binding. I am seeing an issue where, when a cell like this is reused, it queries the first array  I bound to for the number of items despite `.dispose()` being called. Is there something special I need to do to clear a bind on a collection view?

Heres' my `cellForRowAt` code
```swift
override func tableView(_ tableView: UITableView,
                          cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    guard indexPath.section < groups.count else {
      return tableView.dequeueReusableCell(
        withIdentifier: "DefaultTableCell", for: indexPath)
    }

    let group = groups[indexPath.section]
    let scrollingCell = tableView.dequeueReusableCell(
        withIdentifier: "ScrollingTableCell", for: indexPath)
        as! ScrollingTableCell
    scrollingCell.collectionView.index = indexPath.section
    log.debug("filling out scrolling cell at section \(indexPath.section) with group \(group.items.array)")
    group.items.bind(
      to: scrollingCell.collectionView) { items, indexPath, collectionView in
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ItemCell",
                                                        for: indexPath)
        guard let itemCollection = collectionView as? CollapsedItemCollectionView,
          let item = self.groups[itemCollection.index][indexPath.row],
          let itemCell = cell as? ItemCell
          else {
            return cell
          }

        itemCell.marker = marker
        itemCell.fillOutViews()
          
        return itemCell
      }.dispose(in: scrollingCell.bag)

      scrollingCell.collectionView.delegate = self
      return scrollingCell
}
```

And my `ScrollingTableCell` code
```swift
class ScrollingTableCell: UITableViewCell {

  @IBOutlet var collectionView: CollapsedItemCollectionView!

  override func awakeFromNib() {
    super.awakeFromNib()

    collectionView.register(UINib(nibName: "ItemCell", bundle: nil),
                               forCellWithReuseIdentifier: "ItemCell")
  }

  override func prepareForReuse() {
    super.prepareForReuse()
    log.debug("DISPOSING \(self.collectionView.index)")
    bag.dispose()
  }

}
```

**Comment by bmetitiri** [comment]
So after examining the code and documentation again, I see that the `numberOfItems(inSection:)` hook up comes from a call to `reactive.dataSource.feed`, and the docs mention that `You should not set more that one feed property per selector.` I assume that's what I'm running up against? Is the expected use case that a `UICollectionView` or `UITableView` only ever has one array bound to it during it's lifecycle?

**Comment by srdanrasic** [comment]
Looks like you found a bug @bmetitiri :) Disposing the binding should have cleared the data source completely, but it did not. I've just released 6.2.5 that should fix this.

Thanks for the detailed issue report!

**Comment by bmetitiri** [comment]
Hmm, after updating, the same code is giving me a crash after calling `bind` on a collection view that has been reused.

**Comment by srdanrasic** [comment]
That's not good :)

**Comment by garie** [comment]
I think I am seeing the crash as well. I updated to 6.2.5 this morning and get a crash when attempting to use `dataSource`. The crash goes away if I use 6.2.4 instead. 

Stack trace:

```
2017-04-26 10:05:25.634 Rounding[68667:553053] -[Bond.ProtocolProxy numberOfSectionsIn:]: unrecognized selector sent to instance 0x7bfd1e40
2017-04-26 10:05:25.666 Rounding[68667:553053] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Bond.ProtocolProxy numberOfSectionsIn:]: unrecognized selector sent to instance 0x7bfd1e40'
*** First throw call stack:
(
	0   CoreFoundation                      0x033e8494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x02ea2e02 objc_exception_throw + 50
	2   CoreFoundation                      0x033f2253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x0332789d ___forwarding___ + 1037
	4   CoreFoundation                      0x0332746e _CF_forwarding_prep_0 + 14
	5   RoundingView                        0x01dce7d7 _TFC12RoundingView11StackedViewP33_DFD35309960E46F800E54925B3B5150F13populateStackfT_T_ + 135
	6   RoundingView                        0x01dceb72 _TFC12RoundingView11StackedView10reloadDatafT_T_ + 34
	7   RoundingView                        0x01d7d2e3 _TFFe12RoundingViewRx11ReactiveKit14SignalProtocolwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS0_7NoErrorrS1_4binduRd__S_15StackedViewBondrFT2toCS_11StackedView5usingqd___PS0_10Disposable_U3_FQQPS1_7ElementT_ + 899
	8   RoundingView                        0x01d7d827 _TPA__TFFe12RoundingViewRx11ReactiveKit14SignalProtocolwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS0_7NoErrorrS1_4binduRd__S_15StackedViewBondrFT2toCS_11StackedView5usingqd___PS0_10Disposable_U3_FQQPS1_7ElementT_ + 183
	9   ReactiveKit                         0x026592b4 _TFFE11ReactiveKitPS_14SignalProtocol11observeNextFT4withFwx7ElementT__PS_10Disposable_U_FGOS_5EventQQPS0_7ElementQS4_5Error_T_ + 180
	10  ReactiveKit                         0x0266adaf _TPA__TFFE11ReactiveKitPS_14SignalProtocol11observeNextFT4withFwx7ElementT__PS_10Disposable_U_FGOS_5EventQQPS0_7ElementQS4_5Error_T_ + 79
	11  ReactiveKit                         0x02680087 _TFC11ReactiveKit14AtomicObserver2onfGOS_5Eventxq__T_ + 631
	12  ReactiveKit                         0x02665b1b _TFFFFE11ReactiveKitPS_14SignalProtocol5delayFT8intervalSd2onCSo13DispatchQueue_GVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_U_FT_T_ + 251
	13  ReactiveKit                         0x0267e360 _TPA__TFFFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_U_FT_T_ + 80
	14  ReactiveKit                         0x02690531 _TTSf4g___TFZFV11ReactiveKit16ExecutionContextg15immediateOnMainS0_U_FFT_T_T_ + 81
	15  ReactiveKit                         0x0268fd49 _TFZFV11ReactiveKit16ExecutionContextg15immediateOnMainS0_U_FFT_T_T_ + 25
	16  ReactiveKit                         0x02666f36 _TFFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_ + 342
	17  ReactiveKit                         0x0267e302 _TPA__TFFFe11ReactiveKitRxS_14SignalProtocolwx5ErrorzOS_7NoErrorrS0_6tryMapu0_Rd_0_s5ErrorrFFwx7ElementGOS_6Resultqd__qd_0__GVS_6Signalqd__qd_0__U_FGCS_14AtomicObserverQd__Qd_0__PS_10Disposable_U_FGOS_5EventQQPS0_7ElementS2__T__merged + 98
	18  ReactiveKit                         0x0267e298 _TPA__TFFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_ + 40
	19  Bond                                0x0272c00e _TPA__TTRG0_rXFo_iGO11ReactiveKit5EventGV4Bond22Observable2DArrayEventxq__OS_7NoError___XFo_oGS0_GS2_xq__S3____ + 62
	20  Bond                                0x0276a0d3 _TFC4Bond17Observable2DArray7observefT4withFGO11ReactiveKit5EventGVS_22Observable2DArrayEventxq__OS1_7NoError_T__PS1_10Disposable_ + 83
	21  Bond                                0x02729696 _TTWu0_rGC4Bond17Observable2DArrayxq__11ReactiveKit14SignalProtocolS_FS2_7observefT4withFGOS1_5Eventwx7Elementwx5Error_T__PS1_10Disposable__merged + 102
	22  Bond                                0x02727fdb _TTWu0_rGC4Bond17Observable2DArrayxq__11ReactiveKit14SignalProtocolS_FS2_7observefT4withFGOS1_5Eventwx7Elementwx5Error_T__PS1_10Disposable_ + 91
	23  ReactiveKit                         0x02679b64 _TPA__TFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable__merged + 196
	24  ReactiveKit                         0x0266adfb _TPA__TFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_ + 59
	25  ReactiveKit                         0x02689604 _TFV11ReactiveKit6Signal7observefT4withFGOS_5Eventxq__T__PS_10Disposable_ + 340
	26  ReactiveKit                         0x0264d6be _TTWu0_R_s5ErrorrGV11ReactiveKit6Signalxq__S0_14SignalProtocolS0_FS2_7observefT4withFGOS0_5Eventwx7Elementwx5Error_T__PS0_10Disposable_ + 94
	27  ReactiveKit                         0x026594ef _TFE11ReactiveKitPS_14SignalProtocol11observeNextfT4withFwx7ElementT__PS_10Disposable__merged + 111
	28  ReactiveKit                         0x02658a41 _TFE11ReactiveKitPS_14SignalProtocol11observeNextfT4withFwx7ElementT__PS_10Disposable_ + 81
	29  RoundingView                        0x01d7bafe _TFe12RoundingViewRx11ReactiveKit14SignalProtocolwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS0_7NoErrorrS1_4binduRd__S_15StackedViewBondrfT2toCS_11StackedView5usingqd___PS0_10Disposable_ + 2926
	30  RoundingView                        0x01e799cd _TFC12RoundingView30AuditRoundInstanceFindingsView7setDatafT4dataC17RoundingViewModel21FindingGroupViewModel10storyboardGSqCSo12UIStoryboard_15findingActivityCS1_24FindingViewModelActivity_T_ + 541
	31  RoundingView                        0x01dd14c7 _TFC12RoundingView24FindingsGroupTableBonder10cellForRowfT2atV10Foundation9IndexPath9tableViewCSo11UITableView10dataSourcex_CSo15UITableViewCell + 615
	32  RoundingView                        0x01dd239c _TTWuRx4Bond18DataSourceProtocolrGC12RoundingView24FindingsGroupTableBonderx_S1_21TableViewBondExtendedS1_FS3_10cellForRowfT2atV10Foundation9IndexPath9tableViewCSo11UITableView10dataSourcewx10DataSource_CSo15UITableViewCell + 76
	33  RoundingView                        0x01deeaf8 _TFFe12RoundingViewRx11ReactiveKit14SignalProtocolwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS0_7NoErrorrS1_4binduRd__S_21TableViewBondExtendedwd__10DataSourcezWxS2_10DataSource_rFT2toCSo11UITableView5usingqd___PS0_10Disposable_U_FTGSqQQQPS1_7Element10DataSource_S10_CSo11NSIndexPath_CSo15UITableViewCell + 712
	34  RoundingView                        0x01deec83 _TPA__TFFe12RoundingViewRx11ReactiveKit14SignalProtocolwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS0_7NoErrorrS1_4binduRd__S_21TableViewBondExtendedwd__10DataSourcezWxS2_10DataSource_rFT2toCSo11UITableView5usingqd___PS0_10Disposable_U_FTGSqQQQPS1_7Element10DataSource_S10_CSo11NSIndexPath_CSo15UITableViewCell + 163
	35  RoundingView                        0x01deece4 _TTRG__Rx11ReactiveKit14SignalProtocold__12RoundingView21TableViewBondExtendedwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS_7NoErrorwd__10DataSourcezWxS3_10DataSource_rXFo_iGSqWxS3_S9___oCSo11UITableViewoCSo11NSIndexPath_oCSo15UITableViewCell_XFo_iGSqWxS3_S9___iS10_iS11__iS12__ + 84
	36  RoundingView                        0x01deee1c _TPA__TTRG__Rx11ReactiveKit14SignalProtocold__12RoundingView21TableViewBondExtendedwx7Element4Bond23DataSourceEventProtocolwx5ErrorzOS_7NoErrorwd__10DataSourcezWxS3_10DataSource_rXFo_iGSqWxS3_S9___oCSo11UITableViewoCSo11NSIndexPath_oCSo15UITableViewCell_XFo_iGSqWxS3_S9___iS10_iS11__iS12__ + 188
	37  Bond                                0x0275081d _TPA__TFFC4Bond13ProtocolProxy4feedu2_rFT8propertyGC11ReactiveKit8Propertyx_2toV10ObjectiveC8Selector3mapFTxq_q0__q1__PS1_10Disposable_U_FTGCS1_14PublishSubjectT_OS1_7NoError_Q0_Q1__Q2_ + 157
	38  Bond                                0x0275833f _TPA__TFFFC4Bond13ProtocolProxy6signalu2_rFT3forV10ObjectiveC8Selector8dispatchFTGC11ReactiveKit14PublishSubjectq0_OS3_7NoError_xq__q1__GVS3_6Signalq0_S5__U_FGS4_Q1_S5__PS3_10Disposable_U_FTQ_Q0__Q2_ + 79
	39  Bond                                0x0274e59f _TFFC4Bond13ProtocolProxyP33_23028F409340362020B24E8EAAA251BA15registerInvokeru1_rFT3forV10ObjectiveC8Selector5blockFTxq__q0__P11ReactiveKit10Disposable_U_FTFTSiGSqSv__T_GSqFGSqSv_T___T_ + 319
	40  Bond                                0x02757bf1 _TPA__TFFC4Bond13ProtocolProxyP33_23028F409340362020B24E8EAAA251BA15registerInvokeru1_rFT3forV10ObjectiveC8Selector5blockFTxq__q0__P11ReactiveKit10Disposable_U_FTFTSiGSqSv__T_GSqFGSqSv_T___T_ + 113
	41  Bond                                0x02757ca6 _TPA__TTRG1_rXFo_oXFo_dSidGSqSv___oGSqFGSqSv_T____XFo_iTXFo_iTSiGSqSv___iT__GSqFGSqSv_T____iT__ + 166
	42  Bond                                0x02754fb2 _TTSf4n_g_g_n___TFC4Bond13ProtocolProxy6invokefT4withV10ObjectiveC8Selector17argumentExtractorFTSiGSqSv__T_14setReturnValueGSqFGSqSv_T___T_ + 546
	43  Bond                                0x0274dd1e _TToFC4Bond13ProtocolProxy6invokefT4withV10ObjectiveC8Selector17argumentExtractorFTSiGSqSv__T_14setReturnValueGSqFGSqSv_T___T_ + 238
	44  Bond                                0x0271d8a9 -[BNDProtocolProxyBase forwardInvocation:] + 333
	45  CoreFoundation                      0x03327668 ___forwarding___ + 472
	46  CoreFoundation                      0x0332746e _CF_forwarding_prep_0 + 14
	47  UIKit                               0x00484934 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 822
	48  UIKit                               0x00484a7d -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 90
	49  UIKit                               0x00454b32 -[UITableView _updateVisibleCellsNow:isRecursive:] + 3347
	50  UIKit                               0x00473416 __29-[UITableView layoutSubviews]_block_invoke + 52
	51  UIKit                               0x0048e6cc -[UITableView _performWithCachedTraitCollection:] + 88
	52  UIKit                               0x004732eb -[UITableView layoutSubviews] + 214
	53  UIKit                               0x003c93d4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 810
	54  libobjc.A.dylib                     0x02eb7059 -[NSObject performSelector:withObject:] + 70
	55  QuartzCore                          0x08e3f096 -[CALayer layoutSublayers] + 144
	56  QuartzCore                          0x08e328b6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 388
	57  QuartzCore                          0x08e415b0 -[CALayer(CALayerPrivate) layoutBelowIfNeeded] + 44
	58  UIKit                               0x003b6ba4 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1258
	59  UIKit                               0x003b66a6 -[UIView(Hierarchy) layoutIfNeeded] + 82
	60  RoundingView                        0x01d64e39 _TFE12RoundingViewCSo11UITableView15reloadTableviewfT_T_ + 249
	61  RoundingView                        0x01d64f32 _TToFE12RoundingViewCSo11UITableView15reloadTableviewfT_T_ + 34
	62  RoundingView                        0x01dd193e _TFFC12RoundingView24FindingsGroupTableBonder10cellForRowFT2atV10Foundation9IndexPath9tableViewCSo11UITableView10dataSourcex_CSo15UITableViewCellU_FGV4Bond22Observable2DArrayEventC17RoundingViewModel31QuestionAnswerFindingsViewModelCS7_16FindingViewModel_T_ + 302
	63  RoundingView                        0x01dd1b90 _TPA__TFFC12RoundingView24FindingsGroupTableBonder10cellForRowFT2atV10Foundation9IndexPath9tableViewCSo11UITableView10dataSourcex_CSo15UITableViewCellU_FGV4Bond22Observable2DArrayEventC17RoundingViewModel31QuestionAnswerFindingsViewModelCS7_16FindingViewModel_T_ + 64
	64  RoundingView                        0x01dd1be7 _TTRGRx4Bond18DataSourceProtocolrXFo_oGVS_22Observable2DArrayEventC17RoundingViewModel31QuestionAnswerFindingsViewModelCS2_16FindingViewModel___XFo_iGS1_S3_S4____ + 71
	65  RoundingView                        0x01dd1ca7 _TPA__TTRGRx4Bond18DataSourceProtocolrXFo_oGVS_22Observable2DArrayEventC17RoundingViewModel31QuestionAnswerFindingsViewModelCS2_16FindingViewModel___XFo_iGS1_S3_S4____ + 103
	66  ReactiveKit                         0x026592b4 _TFFE11ReactiveKitPS_14SignalProtocol11observeNextFT4withFwx7ElementT__PS_10Disposable_U_FGOS_5EventQQPS0_7ElementQS4_5Error_T_ + 180
	67  ReactiveKit                         0x0266adaf _TPA__TFFE11ReactiveKitPS_14SignalProtocol11observeNextFT4withFwx7ElementT__PS_10Disposable_U_FGOS_5EventQQPS0_7ElementQS4_5Error_T_ + 79
	68  ReactiveKit                         0x02680087 _TFC11ReactiveKit14AtomicObserver2onfGOS_5Eventxq__T_ + 631
	69  ReactiveKit                         0x02665b1b _TFFFFE11ReactiveKitPS_14SignalProtocol5delayFT8intervalSd2onCSo13DispatchQueue_GVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_U_FT_T_ + 251
	70  ReactiveKit                         0x0267e360 _TPA__TFFFFE11ReactiveKitPS_14SignalProtocol9observeInFVS_16ExecutionContextGVS_6Signalwx7Elementwx5Error_U_FGCS_14AtomicObserverQQPS0_7ElementQS6_5Error_PS_10Disposable_U_FGOS_5EventS7_S8__T_U_FT_T_ + 80
	71  ReactiveKit                         0x0268fd7e _TTRXFo___XFdCb___ + 30
	72  libdispatch.dylib                   0x04ed29e3 _dispatch_call_block_and_release + 15
	73  libdispatch.dylib                   0x04ef06ed _dispatch_client_callout + 14
	74  libdispatch.dylib                   0x04ed9286 _dispatch_main_queue_callback_4CF + 689
	75  CoreFoundation                      0x033321be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	76  CoreFoundation                      0x032f0434 __CFRunLoopRun + 2356
	77  CoreFoundation                      0x032ef846 CFRunLoopRunSpecific + 470
	78  CoreFoundation                      0x032ef65b CFRunLoopRunInMode + 123
	79  GraphicsServices                    0x08ce9664 GSEventRunModal + 192
	80  GraphicsServices                    0x08ce94a1 GSEventRun + 104
	81  UIKit                               0x002f8eb9 UIApplicationMain + 160
	82  Rounding                            0x00058bf1 main + 145
	83  libdyld.dylib                       0x04f15a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

`numberOfSectionsIn` is using `feed` as follows:

```
stackedView.reactive.dataSource.feed(
            property: dataSource,
            to: #selector(StackedViewDataSource.numberOfSections(in:)),
            map: { (dataSource: DataSource?, _: StackedView) -> Int in
                dataSource?.numberOfSections ?? 0
        })
```

When updating to 6.2.5, I added the result of `feed` to my `CompositeDisposable`.

I can try to come up with some example code that reproduces the issue if you need it.

**Comment by srdanrasic** [comment]
Thanks for the details @garie, I think I know where the problem is now. Working on it! :)

**Comment by srdanrasic** [comment]
Hi @bmetitiri and @garie, I think I have fixed this now. Please check out v6.2.6. Thanks for being patient :)

**Comment by garie** [comment]
I can confirm the app no longer crashes. I can't speak to the original issue, though, because I don't really understand the symptoms. Thanks!

**Comment by srdanrasic** [comment]
Thanks for the confirmation @garie!

**Comment by artemSydorenko** [comment]
Hi. Original issue still not fixed. I can't rebind collectionView to another array, it still uses the first one.

**Comment by artemSydorenko** [comment]
Currently, I found only one way to reset dataSource's protocolProxy and it is bad way cause it can break something else. But it works:
```
objc_removeAssociatedObjects(collectionView)
```

**Comment by rsbauer** [comment]
Can confirm using Bond v6.3.  Was seeing the following crash when using Bond with a UICollectionView (no nesting in a UITableView or anything like that).

Fatal Exception: NSInvalidArgumentException
-[Bond.ProtocolProxy collectionView:numberOfItemsInSection:]: unrecognized selector sent to instance 0x1c4a72640  

Crashing was happening when shutting down the UIViewController (deinit).  

Bond was initialized like so:
```
self.myDisposable = self.myArray.bind(to: self.myCollectionView) { (arrayItem, indexPath, collectionView) -> UICollectionViewCell in
```
Cleanup performed at shutdown: 
```
if self.myDisposable != nil {
	self.myDisposable!.dispose()
	self.myDisposable = DisposeBag()
	self.myDisposable = nil
}
```
Ended up trying artemSydorenko solution with:
```
objc_removeAssociatedObjects(self.myCollectionView)
```
And so far so good.

**Comment by srdanrasic** [comment]
When rebinding you must dispose previous binding otherwise you end up with multiple bindings and that is not supported.

```swift
let bindingDisposable = SafeSignal<[String]>.just(["A", "B"]).bind(to: vc.collectionView!) { (array, ip, collectionView) -> UICollectionViewCell in
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: ip) as! VC.Cell
    cell.label.text = array[ip.item]
    return cell
}

bindingDisposable.dispose() // important if rebinding

bindingDisposable = SafeSignal<[String]>.just(["A", "C", "B"]).bind(to: vc.collectionView!) { (array, ip, collectionView) -> UICollectionViewCell in
    let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "cell", for: ip) as! VC.Cell
    cell.label.text = array[ip.item]
    return cell
}
```
